version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - ./app:/usr/src/app/
      - /srv/NFS/ms/data/multms-prospective-ext/derivatives:/srv/NFS/ms/data/multms-prospective-ext/derivatives
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    working_dir: /usr/src/app
    command: node app.js